spring.application.name=school
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5434/hogwarts
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=student
spring.datasource.password=chocolatefrog

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update

path.to.avatars.folder=./avatars

avatar.miniature.width=100
avatar.miniature.height=100
